#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node

#figure(
  diagram(
    spacing: 2.4cm,
    node-stroke: 1pt,
    node-corner-radius: 0.5cm,

    // Hlavní kategorie
    node((0, 0), [R], name: <r>),
    node((4, 0), [I], name: <i>),
    node((8, 0), [A], name: <a>),
    node((12, 0), [S], name: <s>),
    node((16, 0), [E], name: <e>),
    node((20, 0), [C], name: <c>),

    // R - Praktický
    node((0, -2), [Strojírenství], name: <r-eng>),
    node((2, -2), [Zemědělství], name: <r-agri>),
    node((4, -2), [Řemesla], name: <r-serv>),
    node((-1, -4), [Mechanika], name: <r-mech>),
    node((1, -4), [Elektrotechnika], name: <r-elec>),
    node((3, -4), [Stavebnictví], name: <r-con>),
    node((5, -4), [Výroba], name: <r-farm>),
    node((7, -4), [Lesnictví], name: <r-for>),
    node((9, -4), [Zahradnictví], name: <r-hort>),
    node((11, -4), [Gastronomie], name: <r-cul>),
    node((13, -4), [Péče o vzhled], name: <r-beauty>),
    node((15, -4), [Řemesla], name: <r-craft>),

    // I - Intelektuální
    node((4, -2), [Informatika], name: <i-it>),
    node((6, -2), [Přírodní vědy], name: <i-sci>),
    node((8, -2), [Zdravotnictví], name: <i-health>),
    node((3, -4), [Programování], name: <i-prog>),
    node((5, -4), [Sítě], name: <i-net>),
    node((7, -4), [Herní průmysl], name: <i-game>),
    node((9, -4), [Chemie], name: <i-chem>),
    node((11, -4), [Biologie], name: <i-bio>),
    node((13, -4), [Fyzika], name: <i-phys>),
    node((15, -4), [Laboratorní medicína], name: <i-lab>),
    node((17, -4), [Zdravotnická technika], name: <i-tech>),
    node((19, -4), [Výživa], name: <i-nutri>),

    // A - Umělecký
    node((8, -2), [Vizuální umění], name: <a-vis>),
    node((10, -2), [Scénické umění], name: <a-perf>),
    node((12, -2), [Hudba], name: <a-music>),
    node((7, -4), [Design], name: <a-des>),
    node((9, -4), [Výtvarné umění], name: <a-fine>),
    node((11, -4), [Fotografie], name: <a-photo>),
    node((13, -4), [Divadlo], name: <a-the>),
    node((15, -4), [Tanec], name: <a-dance>),
    node((17, -4), [Zábava], name: <a-ent>),
    node((19, -4), [Hudební vystupování], name: <a-mperf>),
    node((21, -4), [Hudební pedagogika], name: <a-mteach>),
    node((23, -4), [Hudební technika], name: <a-mtech>),

    // S - Sociální
    node((12, -2), [Pedagogika], name: <s-edu>),
    node((14, -2), [Zdravotnictví], name: <s-health>),
    node((16, -2), [Sociální sféra], name: <s-soc>),
    node((11, -4), [Předškolní], name: <s-pre>),
    node((13, -4), [Vzdělávání], name: <s-elem>),
    node((15, -4), [Zájmové], name: <s-leis>),
    node((17, -4), [Ošetřovatelství], name: <s-nurse>),
    node((19, -4), [Terapie], name: <s-ther>),
    node((21, -4), [Urgentní péče], name: <s-emerg>),
    node((23, -4), [Sociální péče], name: <s-care>),
    node((25, -4), [Poradenství], name: <s-couns>),
    node((27, -4), [Handicap], name: <s-dis>),

    // E - Podnikavý
    node((16, -2), [Obchod], name: <e-biz>),
    node((18, -2), [Management], name: <e-mgmt>),
    node((20, -2), [Pohostinství], name: <e-hosp>),
    node((15, -4), [Prodej], name: <e-sales>),
    node((17, -4), [Maloobchod], name: <e-retail>),
    node((19, -4), [Marketing], name: <e-mkt>),
    node((21, -4), [Provoz], name: <e-ops>),
    node((23, -4), [Projektové řízení], name: <e-proj>),
    node((25, -4), [Personalistika], name: <e-hr>),
    node((27, -4), [Hotelnictví], name: <e-hotel>),
    node((29, -4), [Cestovní ruch], name: <e-tour>),
    node((31, -4), [Strava], name: <e-cat>),

    // C - Organizační
    node((20, -2), [Administrativa], name: <c-admin>),
    node((22, -2), [Finance], name: <c-fin>),
    node((24, -2), [Logistika], name: <c-log>),
    node((19, -4), [Kancelář], name: <c-off>),
    node((21, -4), [Data], name: <c-data>),
    node((23, -4), [Dokumentace], name: <c-doc>),
    node((25, -4), [Účetnictví], name: <c-acc>),
    node((27, -4), [Bankovnictví], name: <c-bank>),
    node((29, -4), [Pojištění], name: <c-ins>),
    node((31, -4), [Sklad], name: <c-wh>),
    node((33, -4), [Přeprava], name: <c-trans>),
    node((35, -4), [Nákup], name: <c-plan>),

    // R linky
    edge(<r>, <r-eng>, [ ], "->"),
    edge(<r>, <r-agri>, [ ], "->"),
    edge(<r>, <r-serv>, [ ], "->"),
    edge(<r-eng>, <r-mech>, [ ], "->"),
    edge(<r-eng>, <r-elec>, [ ], "->"),
    edge(<r-eng>, <r-con>, [ ], "->"),
    edge(<r-agri>, <r-farm>, [ ], "->"),
    edge(<r-agri>, <r-for>, [ ], "->"),
    edge(<r-agri>, <r-hort>, [ ], "->"),
    edge(<r-serv>, <r-cul>, [ ], "->"),
    edge(<r-serv>, <r-beauty>, [ ], "->"),
    edge(<r-serv>, <r-craft>, [ ], "->"),

    // I linky
    edge(<i>, <i-it>, [ ], "->"),
    edge(<i>, <i-sci>, [ ], "->"),
    edge(<i>, <i-health>, [ ], "->"),
    edge(<i-it>, <i-prog>, [ ], "->"),
    edge(<i-it>, <i-net>, [ ], "->"),
    edge(<i-it>, <i-game>, [ ], "->"),
    edge(<i-sci>, <i-chem>, [ ], "->"),
    edge(<i-sci>, <i-bio>, [ ], "->"),
    edge(<i-sci>, <i-phys>, [ ], "->"),
    edge(<i-health>, <i-lab>, [ ], "->"),
    edge(<i-health>, <i-tech>, [ ], "->"),
    edge(<i-health>, <i-nutri>, [ ], "->"),

    // A linky
    edge(<a>, <a-vis>, [ ], "->"),
    edge(<a>, <a-perf>, [ ], "->"),
    edge(<a>, <a-music>, [ ], "->"),
    edge(<a-vis>, <a-des>, [ ], "->"),
    edge(<a-vis>, <a-fine>, [ ], "->"),
    edge(<a-vis>, <a-photo>, [ ], "->"),
    edge(<a-perf>, <a-the>, [ ], "->"),
    edge(<a-perf>, <a-dance>, [ ], "->"),
    edge(<a-perf>, <a-ent>, [ ], "->"),
    edge(<a-music>, <a-mperf>, [ ], "->"),
    edge(<a-music>, <a-mteach>, [ ], "->"),
    edge(<a-music>, <a-mtech>, [ ], "->"),

    // S linky
    edge(<s>, <s-edu>, [ ], "->"),
    edge(<s>, <s-health>, [ ], "->"),
    edge(<s>, <s-soc>, [ ], "->"),
    edge(<s-edu>, <s-pre>, [ ], "->"),
    edge(<s-edu>, <s-elem>, [ ], "->"),
    edge(<s-edu>, <s-leis>, [ ], "->"),
    edge(<s-health>, <s-nurse>, [ ], "->"),
    edge(<s-health>, <s-ther>, [ ], "->"),
    edge(<s-health>, <s-emerg>, [ ], "->"),
    edge(<s-soc>, <s-care>, [ ], "->"),
    edge(<s-soc>, <s-couns>, [ ], "->"),
    edge(<s-soc>, <s-dis>, [ ], "->"),

    // E linky
    edge(<e>, <e-biz>, [ ], "->"),
    edge(<e>, <e-mgmt>, [ ], "->"),
    edge(<e>, <e-hosp>, [ ], "->"),
    edge(<e-biz>, <e-sales>, [ ], "->"),
    edge(<e-biz>, <e-retail>, [ ], "->"),
    edge(<e-biz>, <e-mkt>, [ ], "->"),
    edge(<e-mgmt>, <e-ops>, [ ], "->"),
    edge(<e-mgmt>, <e-proj>, [ ], "->"),
    edge(<e-mgmt>, <e-hr>, [ ], "->"),
    edge(<e-hosp>, <e-hotel>, [ ], "->"),
    edge(<e-hosp>, <e-tour>, [ ], "->"),
    edge(<e-hosp>, <e-cat>, [ ], "->"),

    // C linky
    edge(<c>, <c-admin>, [ ], "->"),
    edge(<c>, <c-fin>, [ ], "->"),
    edge(<c>, <c-log>, [ ], "->"),
    edge(<c-admin>, <c-off>, [ ], "->"),
    edge(<c-admin>, <c-data>, [ ], "->"),
    edge(<c-admin>, <c-doc>, [ ], "->"),
    edge(<c-fin>, <c-acc>, [ ], "->"),
    edge(<c-fin>, <c-bank>, [ ], "->"),
    edge(<c-fin>, <c-ins>, [ ], "->"),
    edge(<c-log>, <c-wh>, [ ], "->"),
    edge(<c-log>, <c-trans>, [ ], "->"),
    edge(<c-log>, <c-plan>, [ ], "->"),
  ),
  caption: [Kariérové zaměření],
)
